#!/usr/bin/env bash

set -euo pipefail

SCRIPT_PATH="$(readlink "$0")"

if [ -z "$SCRIPT_PATH" ]; then
  SCRIPT_PATH="$0"
fi

ROOT_DIR="$(cd "$(dirname "$SCRIPT_PATH")/.." && pwd)"

node "$ROOT_DIR/scripts/core/main.js" "$@"
